# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa2a04eca74d952265ae5bab23626e64557ecbf8b219d24b4fe4601eaf30690e2a66f57c05eafb6dd45cdc8a5d2286df174cb213373fe8d900d51baf1c5a85f

test:
  secret_key_base: 1c65b254598ba8399ae49bb0a0a1588a3e3f47326143b3455b024fc876f91b2ad2389dca8fb7eeca73eb83aeb963e3a123255730733b850703c0de0374013c57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
